### ISSUE TITLE
How use tags?

### ISSUE THREAD

**Issue by faitno** [tschifftner/ansible-role-fail2ban#1]
I wrote tags only config `- { role: tschifftner.ansible-role-fail2ban, tags: ['fail2ban-configure'] }`, but it run all... Could you say, what I do wrong?
My playbook:
```
- hosts: prod
  become: yes
  become_method: sudo
  vars:
    fail2ban_jails:
      - name: 'ssh'
        enabled: true
        port: ssh
        filter: sshd
        logpath: /var/log/auth.log
        bantime: 86400 # 1 day
        maxretry: 2
        action: iptables-multiport
      - name: 'ssh-ddos'
        enabled: true
        port: ssh
        bantime: 86400
        filter: 'sshd-ddos'
        logpath: /var/log/auth.log
        maxretry: 6
        action: iptables-multiport
  roles:
    - { role: tschifftner.ansible-role-fail2ban, tags: ['fail2ban-configure'] }
```
```
ansible 2.1.1.0
```
